f=open("demo.txt","w")
f.write("Hai welcome to the world of books. ")
f.close()
f=open("demo.txt","r")
print(f.read())
f.close()
f=open("demo.txt","a")
f.write("There are different types of books.That are drama,poems,short story,novel,essay,comic etc . I like to read all the type of books.")
f.close()
f=open("demo.txt","r")
print(f.read())
f.close()